# Generated by Django 4.2.16 on 2026-06-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='category',
            field=models.CharField(choices=[('welfare_payment', 'Welfare Payment'), ('loan_emi', 'Loan EMI'), ('curry_payment', 'Curry Payment'), ('deposit', 'Deposit'), ('due', 'Due'), ('membership_fee', 'Membership Fee'), ('share_capital', 'Share Capital'), ('welfare_surcharge', 'Welfare Surcharge (Profit)'), ('welfare_reduction', 'Welfare Grace Period Reduction (Profit)'), ('other_income', 'Other Income'), ('salary', 'Salary Expense'), ('rent', 'Rent Expense'), ('misc_expense', 'Miscellaneous Expense'), ('other_expense', 'Other Expense')], max_length=30),
        ),
    ]
