# Generated by Django 4.2.16 on 2026-07-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_alter_dailyentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='category',
            field=models.CharField(choices=[('welfare_payment', 'Welfare Payment'), ('loan_emi', 'Loan EMI'), ('curry_payment', 'Curry Payment'), ('deposit', 'Deposit'), ('due', 'Due'), ('membership_fee', 'Membership Fee'), ('share_capital', 'Share Capital'), ('welfare_surcharge', 'Welfare Surcharge (Profit)'), ('welfare_reduction', 'Welfare Grace Period Reduction (Profit)'), ('loan_service_charge', 'Loan Service Charge (Profit)'), ('other_income', 'Other Income'), ('salary', 'Salary Expense'), ('rent', 'Rent Expense'), ('current_bill', 'Current Bill'), ('district_counsil', 'District Council'), ('cycle_expense', 'Cycle Expense'), ('printing_stationary', 'Printing & Stationary'), ('office_expense', 'Office Expense'), ('internet', 'Internet'), ('water', 'Water'), ('pothuyokam', 'Pothuyokam'), ('sitting_fees', 'Sitting Fees'), ('welfare_payout', 'Welfare Payout'), ('misc_expense', 'Miscellaneous Expense'), ('other_expense', 'Other Expense')], max_length=30),
        ),
    ]
