# Generated by Django 4.2.16 on 2026-06-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(max_length=20, unique=True)),
                ('group_name', models.CharField(max_length=100)),
                ('chit_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_instalment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField()),
                ('total_members', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chits_chitgroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField()),
                ('prize_won', models.BooleanField(default=False)),
                ('prize_date', models.DateField(blank=True, null=True)),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chit_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='chits.chitgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chit_enrollments', to='members.member')),
            ],
            options={
                'db_table': 'chits_chitenrollment',
                'ordering': ['ticket_number'],
                'unique_together': {('chit_group', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='ChitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='chits.chitenrollment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chits_chitpayment',
                'ordering': ['month_number'],
                'unique_together': {('enrollment', 'month_number')},
            },
        ),
    ]
