# Generated by Django 4.2.16 on 2026-06-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_business_fields'),
        ('chits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitgroup',
            name='commission_percent',
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='guarantor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_guarantor1_set', to='members.member'),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='guarantor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_guarantor2_set', to='members.member'),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='non_member_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='non_member_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='non_member_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='reduction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deduction/reduction beyond grace period (profit of firm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Surcharge amount (profit of firm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='chitgroup',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate/surcharge (flat amount in ₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chitenrollment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chit_enrollments', to='members.member'),
        ),
    ]
