# Generated by Django 4.2.16 on 2026-07-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0002_welfare_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chits_welfareauction',
                'ordering': ['month_number'],
            },
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='division_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chitgroup',
            name='current_month',
            field=models.PositiveIntegerField(default=1, help_text='The current active month of the welfare group'),
        ),
        migrations.AddField(
            model_name='chitgroup',
            name='division_labels',
            field=models.CharField(default='A,B', help_text='Comma-separated labels for divisions', max_length=150),
        ),
        migrations.AddField(
            model_name='chitgroup',
            name='number_of_divisions',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='chitenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('awarded', 'Awarded'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='chitgroup',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='upcoming', max_length=20),
        ),
        migrations.CreateModel(
            name='WelfareAuctionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('winner', 'Winner'), ('caller', 'Caller')], max_length=10)),
                ('division_label', models.CharField(max_length=20)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='chits.welfareauction')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_slots', to='chits.chitenrollment')),
            ],
            options={
                'db_table': 'chits_welfareauctionslot',
                'ordering': ['slot_type'],
            },
        ),
        migrations.AddField(
            model_name='welfareauction',
            name='welfare_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='chits.chitgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='welfareauction',
            unique_together={('welfare_group', 'month_number')},
        ),
    ]
