# Generated by Django 4.2.16 on 2026-07-06 06:01

from django.db import migrations, models


def populate_installment_amount(apps, schema_editor):
    ChitPayment = apps.get_model('chits', 'ChitPayment')
    for payment in ChitPayment.objects.all():
        payment.installment_amount = payment.amount_paid
        if not payment.is_paid:
            payment.amount_paid = 0.00
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0003_welfareauction_chitenrollment_division_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitpayment',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RunPython(populate_installment_amount),
        migrations.AlterField(
            model_name='chitgroup',
            name='division_labels',
            field=models.CharField(blank=True, default='A,B', help_text='Comma-separated labels for divisions', max_length=150),
        ),
        migrations.AlterField(
            model_name='chitgroup',
            name='number_of_divisions',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='chitpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
