# Generated by Django 4.2.16 on 2026-07-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0004_chitpayment_installment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitenrollment',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service charge instead of or in addition to commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='welfareauctionslot',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
