# Generated by Django 4.2.16 on 2026-07-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0005_chitenrollment_service_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitgroup',
            name='processing_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days for processing payouts'),
        ),
    ]
