# Generated by Django 4.2.16 on 2026-07-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0006_chitgroup_processing_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitenrollment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number or transaction reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='payout_payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='cash', max_length=20),
        ),
    ]
