# Generated by Django 4.2.16 on 2026-07-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0007_chitenrollment_cheque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitenrollment',
            name='guarantor1_non_member_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='guarantor1_non_member_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='guarantor2_non_member_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chitenrollment',
            name='guarantor2_non_member_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
