# Generated by Django 4.2.16 on 2026-06-16 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_add_business_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curry_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_slots', models.PositiveIntegerField()),
                ('duration_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'curries_curry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurryParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=True)),
                ('participant_name', models.CharField(blank=True, max_length=150)),
                ('participant_phone', models.CharField(blank=True, max_length=15)),
                ('participant_address', models.TextField(blank=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=150)),
                ('guarantor_phone', models.CharField(blank=True, max_length=15)),
                ('guarantor_address', models.TextField(blank=True)),
                ('guarantor_relation', models.CharField(blank=True, max_length=100)),
                ('ticket_number', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='curries.curry')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curry_participations', to='members.member')),
            ],
            options={
                'db_table': 'curries_participant',
                'ordering': ['ticket_number'],
                'unique_together': {('curry', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='CurryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='curries.curryparticipant')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'curries_payment',
                'ordering': ['month_number'],
                'unique_together': {('participant', 'month_number')},
            },
        ),
    ]
