# Generated by Django 4.2.16 on 2026-06-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.PositiveIntegerField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans', to='members.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='members.member')),
            ],
            options={
                'db_table': 'loans_loan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_no', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('outstanding_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans_loanrepayment',
                'ordering': ['instalment_no'],
            },
        ),
    ]
