# Generated by Django 4.2.16 on 2026-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
