# Generated by Django 4.2.16 on 2026-06-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_add_repayment_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed service charge amount in ₹ (not a percentage)', max_digits=10),
        ),
    ]
