# Generated by Django 4.2.16 on 2026-06-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_add_allowance_model'),
        ('loans', '0003_service_charge_fixed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='guarantor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans2', to='members.member'),
        ),
    ]
