# Generated by Django 4.2.16 on 2026-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_guarantor2'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='urgent_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charge for urgent/early disbursement in ₹', max_digits=10),
        ),
    ]
