# Generated by Django 4.2.16 on 2026-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
