# Generated by Django 4.2.16 on 2026-07-13 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_add_allowance_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='masavari_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
