# Generated by Django 4.2.16 on 2026-06-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('member_joined', 'Member Joined'), ('member_updated', 'Member Updated'), ('chit_enrolled', 'Enrolled in Chit'), ('chit_payment', 'Chit Payment Made'), ('chit_prize', 'Chit Prize Won'), ('loan_applied', 'Loan Applied'), ('loan_approved', 'Loan Approved'), ('loan_repayment', 'Loan Repayment'), ('deposit_made', 'Deposit Made'), ('deposit_withdrawn', 'Deposit Withdrawn'), ('due_paid', 'Due Paid'), ('due_overdue', 'Due Marked Overdue'), ('nominee_added', 'Nominee Added'), ('nominee_updated', 'Nominee Updated'), ('status_changed', 'Status Changed'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities_activitylog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
