# Generated by Django 4.2.16 on 2026-06-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_committee_districtscheme_communitypost_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('member_joined', 'Member Joined'), ('member_updated', 'Member Updated'), ('chit_enrolled', 'Enrolled in Chit'), ('chit_payment', 'Chit Payment Made'), ('chit_prize', 'Chit Prize Won'), ('loan_applied', 'Loan Applied'), ('loan_approved', 'Loan Approved'), ('loan_repayment', 'Loan Repayment'), ('deposit_made', 'Deposit Made'), ('deposit_withdrawn', 'Deposit Withdrawn'), ('due_paid', 'Due Paid'), ('due_overdue', 'Due Marked Overdue'), ('masavari_paid', 'Masavari (Monthly Fee) Paid'), ('nominee_added', 'Nominee Added'), ('nominee_updated', 'Nominee Updated'), ('status_changed', 'Status Changed'), ('other', 'Other')], max_length=30),
        ),
    ]
