# Generated by Django 4.2.16 on 2026-06-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_add_masavari_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='president_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='committee',
            name='president_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='committee',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='committee',
            name='secretary_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='committee',
            name='treasurer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='committee',
            name='treasurer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
