# Generated by Django 4.2.16 on 2026-06-28 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_business_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='due_type',
            field=models.CharField(choices=[('chit_instalment', 'Chit Instalment'), ('loan_emi', 'Loan EMI'), ('membership_renewal', 'Membership Renewal'), ('masavari', 'Masavari (Monthly Due)'), ('penalty', 'Penalty'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='MasavariPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.PositiveIntegerField(help_text='Month number (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Year e.g. 2026')),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masavari_payments', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dues_masavari',
                'ordering': ['-year', '-month'],
                'unique_together': {('member', 'year', 'month')},
            },
        ),
    ]
